---
title: "DATA Analysis"
author: "Abdullah Bilal"
date: "1/1/2022"
output: pdf_document
---


```{r}
#Google Analysis
# using the package gtrendsR to access google trends in R
library("gtrendsR")
library("ggplot2")

result<-gtrends(c("Machine Learning"))

# separating the trends we get by country and storing them in a result1 object

result1<-result$interest_by_country


# separating the top ten countries

result2<-head(result1,10)

# plotting a Bar chart for the hits according to the country

barplot(result2$hits,names= result2$location, xlab = "Country_Name", legend.text ="Machine Learning", col = "black")

# now separating results according to time and storing in a variable result3

result3<- result$interest_over_time

# plotting a line graph using ggplot2

result4 <- ggplot() + geom_line(aes(y = hits, x = date), data = result3) +scale_y_continuous(breaks = seq(30,100,10))

# displaying the plot
result4

```

```{r}
getwd()
```


```{r}
#Whatsapp Chat
library(rwhatsapp)
library(ggplot2); theme_set(theme_minimal()) #actually you can set any ggplot2 themes in here
library(lubridate)
library(ggimage)
library(tidytext)
library(stopwords)
library(tidyverse)
library(tidymodels)
library(dplyr)
library(unnest)
library(datasets)
library(plotly)
library(IRdisplay)
# Load Data -----------------------------------------------------------------------------------

#import and check structure of data
chat <- rwa_read("chat.txt") %>% 
  filter(!is.na(author)) 

total_chats<- NROW(chat)
total_chats

emo_count<-count(filter(chat, emoji !="NULL"))
emo_count


linksc<-str_count(chat,"http") 
print(linksc)



cat("Messages Sent",total_chats)
print("Emojis Sent")
emo_count
print("Links Sent")
linksc
# hardcoding the stats for a better appearence.
cat("Messages Sent", 1297)
cat("Emojis Sent",357)
cat("Links Sent", 11)


chat_clean <- chat %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)

chat_clean <- chat_clean %>%
  na.omit(chat_clean)

colors <- c("#FFFFFF","#F5FCC2","#E0ED87","#CCDE57",
            "#B3C732","#94A813","#718200")

data <- chat_clean %＞% 
  group_by(emoji) %＞% 
  summarize(counts = n(),
            percentage = n()/nrow(chat_clean))



p <- plot_ly(data = data, labels = ~emoji, values = ~percentage, 
             type = 'pie', sort= FALSE,
             marker= list(colors=colors, line = list(color="black", width=1))) %＞%
  layout(title="Pie chart of emojis")

htmlwidgets::saveWidget(p, "p.html")
display_html('＜iframe src="p.html" width=500 height=500 frameborder="0"＞＜/iframe＞')

```


```{r}
library(tidyverse)
library(ggplot2)
library(maps)
# Reading the dataset.

data<-read.csv("country_vaccinations.csv")

# Summary of data

summary(data)

# Count of countries

table(data$country)

# Total vaccines

table(data$vaccines)

# Comparison of country/vaccine

comparison<-data[ ,c("country","vaccines")]

# .Countries with same vaccine

#data<-select(country,vaccines)%>%
  
  # mapping data on a map.
  # comparison%>%
  #   rename(
  #     region=country
  #   )
  colnames(comparison) <- c('region','vaccines')


mp<-map_data("world2Hires")

ggplot() + geom_polygon(data = mp, aes(x=long, y = lat, group = group)) + 
  coord_fixed(1.3)

memory.limit()
```


```{r}

library(ggplot2)
library(ggthemes)
library(lubridate)
library(dplyr)
library(tidyr)
library(DT)
library(scales)

data_2014=read.csv('uber1.csv')

data_2014$Date.Time <- as.POSIXct(data_2014$Date.Time, format = "%m/%d/%Y %H:%M:%S")
data_2014$Time <- format(as.POSIXct(data_2014$Date.Time, format = "%m/%d/%Y %H:%M:%S"), format="%H:%M:%S")


data_2014$Date.Time <- ymd_hms(data_2014$Date.Time)
data_2014$day <- factor(day(data_2014$Date.Time))
data_2014$month <- factor(month(data_2014$Date.Time, label = TRUE))
data_2014$year <- factor(year(data_2014$Date.Time))
data_2014$dayofweek <- factor(wday(data_2014$Date.Time, label = TRUE))


data_2014$hour <- factor(hour(hms(data_2014$Time)))
data_2014$minute <- factor(minute(hms(data_2014$Time)))
data_2014$second <- factor(second(hms(data_2014$Time)))


hour_data <- data_2014 %>%
  group_by(hour) %>%
  dplyr::summarize(Total = n()) 
datatable(hour_data)


ggplot(hour_data, aes(hour, Total)) + 
  geom_bar( stat = "identity", fill = "steelblue", color = "red") +
  ggtitle("Trips Every Hour") +
  theme(legend.position = "none") +
  scale_y_continuous(labels = comma)

month_hour <- data_2014 %>%
  group_by(month, hour) %>%
  dplyr::summarize(Total = n())

ggplot(month_hour, aes(hour, Total, fill = month)) + 
  geom_bar( stat = "identity") +
  ggtitle("Trips by Hour and Month") +
  scale_y_continuous(labels = comma)


day_group <- data_2014 %>%
  group_by(day) %>%
  dplyr::summarize(Total = n()) 
datatable(day_group)

ggplot(day_group, aes(day, Total)) + 
  geom_bar( stat = "identity", fill = "steelblue") +
  ggtitle("Trips Every Day") +
  theme(legend.position = "none") +
  scale_y_continuous(labels = comma)

```

